/**
 * Mock In-Memory Database
 * Simulates MongoDB for testing without actual database
 * 
 * NOTE: Hashed passwords are for "password" (use this for login)
 * Hash: $2b$10$9LszD/9zlmhCmB50k2IuZeZuokzDJzSRK8GqA1RoX7iUcqSbkMI.q
 * Plain text password: password
 */

// Initialize mock database only once
let mockDB = null;

const initializeMockDB = () => {
  if (mockDB) return mockDB;

  mockDB = {
    users: [
      {
        _id: '1',
        firstName: 'Admin',
        lastName: 'User',
        email: 'admin@quizhub.com',
        password: '123456',
        role: 'ADMIN',
        createdAt: new Date(),
      },
      {
        _id: '2',
        firstName: 'Test',
        lastName: 'User',
        email: 'user@quizhub.com',
        password: '123456',
        role: 'USER',
        createdAt: new Date(),
      },
    ],
    quizzes: [
    {
      _id: '1',
      title: 'C Language Fundamentals',
      description: 'Master the basics of C programming language',
      createdBy: '1',
      timeLimit: 600,
      totalQuestions: 5,
      totalMarks: 50,
      passingScore: 60,
      isPublished: true,
      createdAt: new Date(),
    },
    {
      _id: '2',
      title: 'C++ Object-Oriented Programming',
      description: 'Learn C++ and OOP concepts',
      createdBy: '1',
      timeLimit: 600,
      totalQuestions: 5,
      totalMarks: 50,
      passingScore: 65,
      isPublished: true,
      createdAt: new Date(),
    },
    {
      _id: '3',
      title: 'Python Programming',
      description: 'Python basics and advanced concepts',
      createdBy: '1',
      timeLimit: 600,
      totalQuestions: 5,
      totalMarks: 50,
      passingScore: 60,
      isPublished: true,
      createdAt: new Date(),
    },
    {
      _id: '4',
      title: 'Java Fundamentals',
      description: 'Core Java concepts and object-oriented programming',
      createdBy: '1',
      timeLimit: 600,
      totalQuestions: 5,
      totalMarks: 50,
      passingScore: 60,
      isPublished: true,
      createdAt: new Date(),
    },
    {
      _id: '5',
      title: 'JavaScript Basics',
      description: 'Test your knowledge of JavaScript fundamentals',
      createdBy: '1',
      timeLimit: 600,
      totalQuestions: 5,
      totalMarks: 50,
      passingScore: 60,
      isPublished: true,
      createdAt: new Date(),
    },
    {
      _id: '6',
      title: 'SQL Database Fundamentals',
      description: 'Master SQL queries and database concepts',
      createdBy: '1',
      timeLimit: 600,
      totalQuestions: 5,
      totalMarks: 50,
      passingScore: 60,
      isPublished: true,
      createdAt: new Date(),
    },
  ],
  questions: [
    // C Language Questions (Quiz 1)
    {
      _id: '1',
      quizId: '1',
      questionNumber: 1,
      questionText: 'What is the correct syntax for variable declaration in C?',
      options: ['int a;', 'a int;', 'declare int a;', 'var a;'],
      correctOptionIndex: 0,
      marks: 10,
    },
    {
      _id: '2',
      quizId: '1',
      questionNumber: 2,
      questionText: 'Which function is used to print output in C?',
      options: ['print()', 'printf()', 'cout()', 'output()'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '3',
      quizId: '1',
      questionNumber: 3,
      questionText: 'What is a pointer in C?',
      options: ['A variable that stores a value', 'A variable that stores a memory address', 'A function parameter', 'A type of array'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '4',
      quizId: '1',
      questionNumber: 4,
      questionText: 'Which operator is used to access a value pointed by a pointer?',
      options: ['*', '&', '->', '.'],
      correctOptionIndex: 0,
      marks: 10,
    },
    {
      _id: '5',
      quizId: '1',
      questionNumber: 5,
      questionText: 'What is the typical size of an int in C?',
      options: ['2 bytes', '4 bytes', '8 bytes', 'It depends on the system'],
      correctOptionIndex: 3,
      marks: 10,
    },
    // C++ Questions (Quiz 2)
    {
      _id: '6',
      quizId: '2',
      questionNumber: 1,
      questionText: 'What is the main difference between a struct and a class in C++?',
      options: ['Struct has no methods', 'Class is used for objects only', 'Default access level is different', 'There is no difference'],
      correctOptionIndex: 2,
      marks: 10,
    },
    {
      _id: '7',
      quizId: '2',
      questionNumber: 2,
      questionText: 'Which feature makes C++ object-oriented?',
      options: ['Templates', 'Inheritance and Polymorphism', 'Pointers', 'Function overloading'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '8',
      quizId: '2',
      questionNumber: 3,
      questionText: 'What is a virtual function in C++?',
      options: ['A function that does not exist', 'A function that can be overridden by derived classes', 'A function that is never called', 'A static function'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '9',
      quizId: '2',
      questionNumber: 4,
      questionText: 'What is the purpose of a constructor?',
      options: ['To destroy an object', 'To initialize an object', 'To copy an object', 'To compare objects'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '10',
      quizId: '2',
      questionNumber: 5,
      questionText: 'Which keyword is used for inheritance in C++?',
      options: ['inherit', 'extend', 'implements', ':'],
      correctOptionIndex: 3,
      marks: 10,
    },
    // Python Questions (Quiz 3)
    {
      _id: '11',
      quizId: '3',
      questionNumber: 1,
      questionText: 'What is the correct syntax for creating a dictionary in Python?',
      options: ['{key: value}', '{"key": "value"}', '(key, value)', '[key, value]'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '12',
      quizId: '3',
      questionNumber: 2,
      questionText: 'How do you create a list in Python?',
      options: ['(1, 2, 3)', '[1, 2, 3]', '{1, 2, 3}', '1, 2, 3'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '13',
      quizId: '3',
      questionNumber: 3,
      questionText: 'What does pip stand for?',
      options: ['Python Input Package', 'Pip Installs Packages', 'Python Installation Package', 'Package Integration Protocol'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '14',
      quizId: '3',
      questionNumber: 4,
      questionText: 'Which data type in Python is immutable?',
      options: ['List', 'Dictionary', 'Tuple', 'Set'],
      correctOptionIndex: 2,
      marks: 10,
    },
    {
      _id: '15',
      quizId: '3',
      questionNumber: 5,
      questionText: 'What does the len() function return?',
      options: ['The type of the object', 'The length of an object', 'The memory size', 'The hash value'],
      correctOptionIndex: 1,
      marks: 10,
    },
    // Java Questions (Quiz 4)
    {
      _id: '16',
      quizId: '4',
      questionNumber: 1,
      questionText: 'Which keyword is used to create a class in Java?',
      options: ['object', 'class', 'Class', 'define'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '17',
      quizId: '4',
      questionNumber: 2,
      questionText: 'What is the entry point of a Java program?',
      options: ['run()', 'start()', 'main()', 'init()'],
      correctOptionIndex: 2,
      marks: 10,
    },
    {
      _id: '18',
      quizId: '4',
      questionNumber: 3,
      questionText: 'What is the purpose of the static keyword in Java?',
      options: ['Makes a variable constant', 'Belongs to the class, not an instance', 'Hides a variable', 'Speeds up code'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '19',
      quizId: '4',
      questionNumber: 4,
      questionText: 'Which of these is a feature of Java?',
      options: ['Pointers', 'Multiple Inheritance', 'Object-Oriented Programming', 'Manual Memory Management'],
      correctOptionIndex: 2,
      marks: 10,
    },
    {
      _id: '20',
      quizId: '4',
      questionNumber: 5,
      questionText: 'What is the default value of a String variable in Java?',
      options: ['" "', 'empty', 'null', '0'],
      correctOptionIndex: 2,
      marks: 10,
    },
    // JavaScript Questions (Quiz 5)
    {
      _id: '21',
      quizId: '5',
      questionNumber: 1,
      questionText: 'What does "const" stand for in JavaScript?',
      options: ['Constant', 'Construct', 'Constructor', 'Continue'],
      correctOptionIndex: 0,
      marks: 10,
    },
    {
      _id: '22',
      quizId: '5',
      questionNumber: 2,
      questionText: 'Which method returns a new array?',
      options: ['push()', 'map()', 'shift()', 'pop()'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '23',
      quizId: '5',
      questionNumber: 3,
      questionText: 'What is the output of typeof null?',
      options: ['null', 'object', 'undefined', 'string'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '24',
      quizId: '5',
      questionNumber: 4,
      questionText: 'How do you create a function in JavaScript?',
      options: ['function myFunc() {}', 'def myFunc():', 'func myFunc() {}', 'function: myFunc()'],
      correctOptionIndex: 0,
      marks: 10,
    },
    {
      _id: '25',
      quizId: '5',
      questionNumber: 5,
      questionText: 'What is the correct way to check if a variable is an array?',
      options: ['typeof arr === "array"', 'arr instanceof Array', 'isArray(arr)', 'arr.isArray()'],
      correctOptionIndex: 1,
      marks: 10,
    },
    // SQL Questions (Quiz 6)
    {
      _id: '26',
      quizId: '6',
      questionNumber: 1,
      questionText: 'Which SQL statement is used to retrieve data from a database?',
      options: ['GET', 'RETRIEVE', 'SELECT', 'FETCH'],
      correctOptionIndex: 2,
      marks: 10,
    },
    {
      _id: '27',
      quizId: '6',
      questionNumber: 2,
      questionText: 'What does SQL stand for?',
      options: ['Structured Query Language', 'Standard Query Language', 'Special Query Language', 'System Query Language'],
      correctOptionIndex: 0,
      marks: 10,
    },
    {
      _id: '28',
      quizId: '6',
      questionNumber: 3,
      questionText: 'Which keyword is used to sort results in SQL?',
      options: ['SORT', 'ORDER BY', 'GROUP BY', 'ARRANGE'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '29',
      quizId: '6',
      questionNumber: 4,
      questionText: 'What is a primary key in a database?',
      options: ['A password', 'A unique identifier for each record', 'A backup key', 'An encryption key'],
      correctOptionIndex: 1,
      marks: 10,
    },
    {
      _id: '30',
      quizId: '6',
      questionNumber: 5,
      questionText: 'Which SQL keyword is used to filter records based on conditions?',
      options: ['FILTER', 'WHERE', 'SEARCH', 'MATCH'],
      correctOptionIndex: 1,
      marks: 10,
    },
  ],
    results: [],
  };

  return mockDB;
};

let nextUserId = 3;
let nextQuizId = 7;
let nextQuestionId = 31;
let nextResultId = 1;

module.exports = {
  get mockDB() {
    if (!mockDB) {
      initializeMockDB();
    }
    return mockDB;
  },
  initializeMockDB,
  getNextUserId: () => String(nextUserId++),
  getNextQuizId: () => String(nextQuizId++),
  getNextQuestionId: () => String(nextQuestionId++),
  getNextResultId: () => String(nextResultId++),
};
